# .github/labeler.yml

# Add 'app' label to application-related changes
app:
  - changed-files: ['Apps/*', 'src/apps/*', 'apps/*']

# Add 'bug' label to bug-related changes
bug:
  - changed-files: ['*bug*', '*error*', '*fix*', '*issue*', 'src/errors/*', 'docs/bugs/*']

# Add 'feature' label to feature-related changes
feature:
  - changed-files: ['*features*', '*enhancements*', '*improvements*', '*additions*', 'src/features/*', 'docs/features/*']

# Add 'documentation' label to documentation-related changes
documentation:
  - changed-files: ['docs/**', 'docs/*', 'guides/*', '**/*.md']

# Add 'tests' label to test-related changes
tests:
  - changed-files: ['*test*', 'tests/*', 'spec/*', '*.spec.*', '*.test.*']

# Add 'dependencies' label to dependency-related changes
dependencies:
  - changed-files: ['package.json', 'requirements.txt', 'Gemfile', 'Cargo.toml', '*.lock']

# Add 'ci' label to CI configuration changes
ci:
  - changed-files: ['.github/workflows/*', '.travis.yml', 'circle.yml']

# Add 'configuration' label to configuration files
configuration:
  - changed-files: ['*.config.*', '*.conf', '*.yaml', '*.yml', 'config/*']

# Add 'performance' label to performance improvements
performance:
  - changed-files: ['*performance*', '*speed*', '*optimize*', 'src/performance/*']

# Add 'refactor' label to refactoring changes
refactor:
  - changed-files: ['*refactor*', '*cleanup*', '*restructure*', 'src/refactor/*']

# Add 'styling' label to styling changes
styling:
  - changed-files: ['*style*', '*css*', '*scss*', '*less*', '*ui*', '*ux*', 'src/styles/*', 'styles/*', '*.css', '*.scss', '*.less']

# Add 'root' label to any root file changes
root:
  - changed-files: ['*']

# Add 'AnyChange' label to any changes within the entire repository
AnyChange:
  - changed-files: ['**']
